name: Application Build

on:
  push:
    branches: develop

jobs:
  release:
    name: Run build and deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    container:
      image: ghcr.io/aecomet/pnpm-base:22.3.0
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PERSONAL_ACCESS_TOKEN_FOR_ACTIONS }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build app
        run: pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
          publish_branch: master
          commit_message: 'build: app release(last commit: ${{ github.event.head_commit.message }})'

      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-image:
    name: Build image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    container:
      image: ghcr.io/aecomet/pnpm-base:22.3.0
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PERSONAL_ACCESS_TOKEN_FOR_ACTIONS }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/portfolio
          tags: |
            type=raw,value=latest

      - name: Build and Push a Image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
